version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    ports:
      - '8005:80'
    volumes:
      - storage_volume:/var/www/html/storage
      - uploads_volume:/var/www/html/public/uploads
    environment:
      - APP_ENV=production
      - APP_URL=https://edu.nexorait.lk
    command: >
      sh -c "
      chown -R www-data:www-data /var/www/html/storage /var/www/html/public/uploads &&
      chmod -R 775 /var/www/html/storage /var/www/html/public/uploads &&
      apache2-foreground
      "

volumes:
  storage_volume:
  uploads_volume:
